# Generated by Django 3.0.4 on 2020-03-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='s_percent',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
